"""NOVA COLUNAS

Revision ID: 07d4343cd8ee
Revises: 8cb9b6d87e74
Create Date: 2026-03-12 17:57:18.911758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d4343cd8ee'
down_revision = '8cb9b6d87e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_entrega', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('status_entrega')

    # ### end Alembic commands ###
