"""novas colunas

Revision ID: 8cb9b6d87e74
Revises: 4a2e002a6b78
Create Date: 2026-03-11 19:29:30.165172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb9b6d87e74'
down_revision = '4a2e002a6b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprador_nome', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('observacao')
        batch_op.drop_column('comprador_nome')

    # ### end Alembic commands ###
